name: textium
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

#flutter 3.10.6
environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  bloc_concurrency: ^0.2.2
  cloud_firestore: ^4.8.4
  equatable: ^2.0.5
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.0
  intl: ^0.18.0
  shared_preferences: ^2.2.0
  share_plus: ^7.0.2
  stack_trace: ^1.11.0
  flutter_secure_storage: ^8.0.0
  local_auth: ^2.1.6
  google_sign_in: ^6.1.4
  firebase_messaging: ^14.6.5
  package_info_plus: ^4.0.2
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true
  main_locale: ru
  arb_dir: lib/core/l10n/arb
  output_dir: lib/core/l10n/generated
